export { default as pawmateWireframe } from "./pawmateWireframe.png";
export { default as pawMateCode } from "./pawMateCode.png";
export { default as pawMateCode2 } from "./pawMateCode2.png";
export { default as pawMateCode3 } from "./pawMateCode3.png";
export { default as PawMateInformationArchitectureMap } from "./PawMateInformationArchitectureMap.png";
export { default as pawMate_PrototypeFigma } from "./pawMate_PrototypeFigma.png";
export { default as mockupPawMateApp } from "./mockupPawMateApp.png";
export { default as PawMateResponsiveScreens } from "./PawMateResponsiveScreens.png";
export { default as PawMateScreensApp } from "./PawMateScreensApp.png";
